# Generated by Django 3.0.8 on 2020-10-19 07:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('travelit', '0002_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=300)),
                ('place', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
